# Generated by Django 2.1.7 on 2022-08-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220823_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 23, 11, 37, 39, 743532)),
        ),
    ]
