# Generated by Django 2.1.7 on 2022-08-26 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220823_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 26, 17, 7, 50, 252001)),
        ),
    ]
